# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.2.7
maven_group=com.panyaaa256

# Dependencies
fabric_api_version=0.141.4+1.21.11
yacl_version=3.8.2+1.21.11-fabric

# Soft dependencies (sakura-ryoko fork, via Modrinth maven)
litematica_version=0.26.11
malilib_version=0.27.16
iris_version=1.10.7+1.21.11-fabric

# Test dependencies
junit_version=6.1.3
